<?php

use Illuminate\Database\Seeder;
use App\Country;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $us = Country::where('iso2_code', 'US')->firstOrFail();
        $ca = Country::where('iso2_code', 'CA')->firstOrFail();
        $de = Country::where('iso2_code', 'DE')->firstOrFail();
        $at = Country::where('iso2_code', 'AT')->firstOrFail();
        $ch = Country::where('iso2_code', 'CH')->firstOrFail();
        $es = Country::where('iso2_code', 'ES')->firstOrFail();
        $fr = Country::where('iso2_code', 'FR')->firstOrFail();
        $ro = Country::where('iso2_code', 'RO')->firstOrFail();
        $fi = Country::where('iso2_code', 'FI')->firstOrFail();
        $ee = Country::where('iso2_code', 'EE')->firstOrFail();
        $lv = Country::where('iso2_code', 'LV')->firstOrFail();
        $lt = Country::where('iso2_code', 'LT')->firstOrFail();


        DB::table('regions')->insert([
            ['country_id' => $us->id, 'code' => 'AL', 'name' => 'Alabama'],
            ['country_id' => $us->id, 'code' => 'AK', 'name' => 'Alaska'],
            ['country_id' => $us->id, 'code' => 'AS', 'name' => 'American Samoa'],
            ['country_id' => $us->id, 'code' => 'AZ', 'name' => 'Arizona'],
            ['country_id' => $us->id, 'code' => 'AR', 'name' => 'Arkansas'],
            ['country_id' => $us->id, 'code' => 'AF', 'name' => 'Armed Forces Africa'],
            ['country_id' => $us->id, 'code' => 'AA', 'name' => 'Armed Forces Americas'],
            ['country_id' => $us->id, 'code' => 'AC', 'name' => 'Armed Forces Canada'],
            ['country_id' => $us->id, 'code' => 'AE', 'name' => 'Armed Forces Europe'],
            ['country_id' => $us->id, 'code' => 'AM', 'name' => 'Armed Forces Middle East'],
            ['country_id' => $us->id, 'code' => 'AP', 'name' => 'Armed Forces Pacific'],
            ['country_id' => $us->id, 'code' => 'CA', 'name' => 'California'],
            ['country_id' => $us->id, 'code' => 'CO', 'name' => 'Colorado'],
            ['country_id' => $us->id, 'code' => 'CT', 'name' => 'Connecticut'],
            ['country_id' => $us->id, 'code' => 'DE', 'name' => 'Delaware'],
            ['country_id' => $us->id, 'code' => 'DC', 'name' => 'District of Columbia'],
            ['country_id' => $us->id, 'code' => 'FM', 'name' => 'Federated States Of Micronesia'],
            ['country_id' => $us->id, 'code' => 'FL', 'name' => 'Florida'],
            ['country_id' => $us->id, 'code' => 'GA', 'name' => 'Georgia'],
            ['country_id' => $us->id, 'code' => 'GU', 'name' => 'Guam'],
            ['country_id' => $us->id, 'code' => 'HI', 'name' => 'Hawaii'],
            ['country_id' => $us->id, 'code' => 'ID', 'name' => 'Idaho'],
            ['country_id' => $us->id, 'code' => 'IL', 'name' => 'Illinois'],
            ['country_id' => $us->id, 'code' => 'IN', 'name' => 'Indiana'],
            ['country_id' => $us->id, 'code' => 'IA', 'name' => 'Iowa'],
            ['country_id' => $us->id, 'code' => 'KS', 'name' => 'Kansas'],
            ['country_id' => $us->id, 'code' => 'KY', 'name' => 'Kentucky'],
            ['country_id' => $us->id, 'code' => 'LA', 'name' => 'Louisiana'],
            ['country_id' => $us->id, 'code' => 'ME', 'name' => 'Maine'],
            ['country_id' => $us->id, 'code' => 'MH', 'name' => 'Marshall Islands'],
            ['country_id' => $us->id, 'code' => 'MD', 'name' => 'Maryland'],
            ['country_id' => $us->id, 'code' => 'MA', 'name' => 'Massachusetts'],
            ['country_id' => $us->id, 'code' => 'MI', 'name' => 'Michigan'],
            ['country_id' => $us->id, 'code' => 'MN', 'name' => 'Minnesota'],
            ['country_id' => $us->id, 'code' => 'MS', 'name' => 'Mississippi'],
            ['country_id' => $us->id, 'code' => 'MO', 'name' => 'Missouri'],
            ['country_id' => $us->id, 'code' => 'MT', 'name' => 'Montana'],
            ['country_id' => $us->id, 'code' => 'NE', 'name' => 'Nebraska'],
            ['country_id' => $us->id, 'code' => 'NV', 'name' => 'Nevada'],
            ['country_id' => $us->id, 'code' => 'NH', 'name' => 'New Hampshire'],
            ['country_id' => $us->id, 'code' => 'NJ', 'name' => 'New Jersey'],
            ['country_id' => $us->id, 'code' => 'NM', 'name' => 'New Mexico'],
            ['country_id' => $us->id, 'code' => 'NY', 'name' => 'New York'],
            ['country_id' => $us->id, 'code' => 'NC', 'name' => 'North Carolina'],
            ['country_id' => $us->id, 'code' => 'ND', 'name' => 'North Dakota'],
            ['country_id' => $us->id, 'code' => 'MP', 'name' => 'Northern Mariana Islands'],
            ['country_id' => $us->id, 'code' => 'OH', 'name' => 'Ohio'],
            ['country_id' => $us->id, 'code' => 'OK', 'name' => 'Oklahoma'],
            ['country_id' => $us->id, 'code' => 'OR', 'name' => 'Oregon'],
            ['country_id' => $us->id, 'code' => 'PW', 'name' => 'Palau'],
            ['country_id' => $us->id, 'code' => 'PA', 'name' => 'Pennsylvania'],
            ['country_id' => $us->id, 'code' => 'PR', 'name' => 'Puerto Rico'],
            ['country_id' => $us->id, 'code' => 'RI', 'name' => 'Rhode Island'],
            ['country_id' => $us->id, 'code' => 'SC', 'name' => 'South Carolina'],
            ['country_id' => $us->id, 'code' => 'SD', 'name' => 'South Dakota'],
            ['country_id' => $us->id, 'code' => 'TN', 'name' => 'Tennessee'],
            ['country_id' => $us->id, 'code' => 'TX', 'name' => 'Texas'],
            ['country_id' => $us->id, 'code' => 'UT', 'name' => 'Utah'],
            ['country_id' => $us->id, 'code' => 'VT', 'name' => 'Vermont'],
            ['country_id' => $us->id, 'code' => 'VI', 'name' => 'Virgin Islands'],
            ['country_id' => $us->id, 'code' => 'VA', 'name' => 'Virginia'],
            ['country_id' => $us->id, 'code' => 'WA', 'name' => 'Washington'],
            ['country_id' => $us->id, 'code' => 'WV', 'name' => 'West Virginia'],
            ['country_id' => $us->id, 'code' => 'WI', 'name' => 'Wisconsin'],
            ['country_id' => $us->id, 'code' => 'WY', 'name' => 'Wyoming'],
            ['country_id' => $ca->id, 'code' => 'AB', 'name' => 'Alberta'],
            ['country_id' => $ca->id, 'code' => 'BC', 'name' => 'British Columbia'],
            ['country_id' => $ca->id, 'code' => 'MB', 'name' => 'Manitoba'],
            ['country_id' => $ca->id, 'code' => 'NL', 'name' => 'Newfoundland and Labrador'],
            ['country_id' => $ca->id, 'code' => 'NB', 'name' => 'New Brunswick'],
            ['country_id' => $ca->id, 'code' => 'NS', 'name' => 'Nova Scotia'],
            ['country_id' => $ca->id, 'code' => 'NT', 'name' => 'Northwest Territories'],
            ['country_id' => $ca->id, 'code' => 'NU', 'name' => 'Nunavut'],
            ['country_id' => $ca->id, 'code' => 'ON', 'name' => 'Ontario'],
            ['country_id' => $ca->id, 'code' => 'PE', 'name' => 'Prince Edward Island'],
            ['country_id' => $ca->id, 'code' => 'QC', 'name' => 'Quebec'],
            ['country_id' => $ca->id, 'code' => 'SK', 'name' => 'Saskatchewan'],
            ['country_id' => $ca->id, 'code' => 'YT', 'name' => 'Yukon Territory'],
            ['country_id' => $de->id, 'code' => 'NDS', 'name' => 'Niedersachsen'],
            ['country_id' => $de->id, 'code' => 'BAW', 'name' => 'Baden-Württemberg'],
            ['country_id' => $de->id, 'code' => 'BAY', 'name' => 'Bayern'],
            ['country_id' => $de->id, 'code' => 'BER', 'name' => 'Berlin'],
            ['country_id' => $de->id, 'code' => 'BRG', 'name' => 'Brandenburg'],
            ['country_id' => $de->id, 'code' => 'BRE', 'name' => 'Bremen'],
            ['country_id' => $de->id, 'code' => 'HAM', 'name' => 'Hamburg'],
            ['country_id' => $de->id, 'code' => 'HES', 'name' => 'Hessen'],
            ['country_id' => $de->id, 'code' => 'MEC', 'name' => 'Mecklenburg-Vorpommern'],
            ['country_id' => $de->id, 'code' => 'NRW', 'name' => 'Nordrhein-Westfalen'],
            ['country_id' => $de->id, 'code' => 'RHE', 'name' => 'Rheinland-Pfalz'],
            ['country_id' => $de->id, 'code' => 'SAR', 'name' => 'Saarland'],
            ['country_id' => $de->id, 'code' => 'SAS', 'name' => 'Sachsen'],
            ['country_id' => $de->id, 'code' => 'SAC', 'name' => 'Sachsen-Anhalt'],
            ['country_id' => $de->id, 'code' => 'SCN', 'name' => 'Schleswig-Holstein'],
            ['country_id' => $de->id, 'code' => 'THE', 'name' => 'Thüringen'],
            ['country_id' => $at->id, 'code' => 'WI', 'name' => 'Wien'],
            ['country_id' => $at->id, 'code' => 'NO', 'name' => 'Niederösterreich'],
            ['country_id' => $at->id, 'code' => 'OO', 'name' => 'Oberösterreich'],
            ['country_id' => $at->id, 'code' => 'SB', 'name' => 'Salzburg'],
            ['country_id' => $at->id, 'code' => 'KN', 'name' => 'Kärnten'],
            ['country_id' => $at->id, 'code' => 'ST', 'name' => 'Steiermark'],
            ['country_id' => $at->id, 'code' => 'TI', 'name' => 'Tirol'],
            ['country_id' => $at->id, 'code' => 'BL', 'name' => 'Burgenland'],
            ['country_id' => $at->id, 'code' => 'VB', 'name' => 'Vorarlberg'],
            ['country_id' => $ch->id, 'code' => 'AG', 'name' => 'Aargau'],
            ['country_id' => $ch->id, 'code' => 'AI', 'name' => 'Appenzell Innerrhoden'],
            ['country_id' => $ch->id, 'code' => 'AR', 'name' => 'Appenzell Ausserrhoden'],
            ['country_id' => $ch->id, 'code' => 'BE', 'name' => 'Bern'],
            ['country_id' => $ch->id, 'code' => 'BL', 'name' => 'Basel-Landschaft'],
            ['country_id' => $ch->id, 'code' => 'BS', 'name' => 'Basel-Stadt'],
            ['country_id' => $ch->id, 'code' => 'FR', 'name' => 'Freiburg'],
            ['country_id' => $ch->id, 'code' => 'GE', 'name' => 'Genf'],
            ['country_id' => $ch->id, 'code' => 'GL', 'name' => 'Glarus'],
            ['country_id' => $ch->id, 'code' => 'GR', 'name' => 'Graubünden'],
            ['country_id' => $ch->id, 'code' => 'JU', 'name' => 'Jura'],
            ['country_id' => $ch->id, 'code' => 'LU', 'name' => 'Luzern'],
            ['country_id' => $ch->id, 'code' => 'NE', 'name' => 'Neuenburg'],
            ['country_id' => $ch->id, 'code' => 'NW', 'name' => 'Nidwalden'],
            ['country_id' => $ch->id, 'code' => 'OW', 'name' => 'Obwalden'],
            ['country_id' => $ch->id, 'code' => 'SG', 'name' => 'St. Gallen'],
            ['country_id' => $ch->id, 'code' => 'SH', 'name' => 'Schaffhausen'],
            ['country_id' => $ch->id, 'code' => 'SO', 'name' => 'Solothurn'],
            ['country_id' => $ch->id, 'code' => 'SZ', 'name' => 'Schwyz'],
            ['country_id' => $ch->id, 'code' => 'TG', 'name' => 'Thurgau'],
            ['country_id' => $ch->id, 'code' => 'TI', 'name' => 'Tessin'],
            ['country_id' => $ch->id, 'code' => 'UR', 'name' => 'Uri'],
            ['country_id' => $ch->id, 'code' => 'VD', 'name' => 'Waadt'],
            ['country_id' => $ch->id, 'code' => 'VS', 'name' => 'Wallis'],
            ['country_id' => $ch->id, 'code' => 'ZG', 'name' => 'Zug'],
            ['country_id' => $ch->id, 'code' => 'ZH', 'name' => 'Zürich'],
            ['country_id' => $es->id, 'code' => 'A Coruсa', 'name' => 'A Coruña'],
            ['country_id' => $es->id, 'code' => 'Alava', 'name' => 'Alava'],
            ['country_id' => $es->id, 'code' => 'Albacete', 'name' => 'Albacete'],
            ['country_id' => $es->id, 'code' => 'Alicante', 'name' => 'Alicante'],
            ['country_id' => $es->id, 'code' => 'Almeria', 'name' => 'Almeria'],
            ['country_id' => $es->id, 'code' => 'Asturias', 'name' => 'Asturias'],
            ['country_id' => $es->id, 'code' => 'Avila', 'name' => 'Avila'],
            ['country_id' => $es->id, 'code' => 'Badajoz', 'name' => 'Badajoz'],
            ['country_id' => $es->id, 'code' => 'Baleares', 'name' => 'Baleares'],
            ['country_id' => $es->id, 'code' => 'Barcelona', 'name' => 'Barcelona'],
            ['country_id' => $es->id, 'code' => 'Burgos', 'name' => 'Burgos'],
            ['country_id' => $es->id, 'code' => 'Caceres', 'name' => 'Caceres'],
            ['country_id' => $es->id, 'code' => 'Cadiz', 'name' => 'Cadiz'],
            ['country_id' => $es->id, 'code' => 'Cantabria', 'name' => 'Cantabria'],
            ['country_id' => $es->id, 'code' => 'Castellon', 'name' => 'Castellon'],
            ['country_id' => $es->id, 'code' => 'Ceuta', 'name' => 'Ceuta'],
            ['country_id' => $es->id, 'code' => 'Ciudad Real', 'name' => 'Ciudad Real'],
            ['country_id' => $es->id, 'code' => 'Cordoba', 'name' => 'Cordoba'],
            ['country_id' => $es->id, 'code' => 'Cuenca', 'name' => 'Cuenca'],
            ['country_id' => $es->id, 'code' => 'Girona', 'name' => 'Girona'],
            ['country_id' => $es->id, 'code' => 'Granada', 'name' => 'Granada'],
            ['country_id' => $es->id, 'code' => 'Guadalajara', 'name' => 'Guadalajara'],
            ['country_id' => $es->id, 'code' => 'Guipuzcoa', 'name' => 'Guipuzcoa'],
            ['country_id' => $es->id, 'code' => 'Huelva', 'name' => 'Huelva'],
            ['country_id' => $es->id, 'code' => 'Huesca', 'name' => 'Huesca'],
            ['country_id' => $es->id, 'code' => 'Jaen', 'name' => 'Jaen'],
            ['country_id' => $es->id, 'code' => 'La Rioja', 'name' => 'La Rioja'],
            ['country_id' => $es->id, 'code' => 'Las Palmas', 'name' => 'Las Palmas'],
            ['country_id' => $es->id, 'code' => 'Leon', 'name' => 'Leon'],
            ['country_id' => $es->id, 'code' => 'Lleida', 'name' => 'Lleida'],
            ['country_id' => $es->id, 'code' => 'Lugo', 'name' => 'Lugo'],
            ['country_id' => $es->id, 'code' => 'Madrid', 'name' => 'Madrid'],
            ['country_id' => $es->id, 'code' => 'Malaga', 'name' => 'Malaga'],
            ['country_id' => $es->id, 'code' => 'Melilla', 'name' => 'Melilla'],
            ['country_id' => $es->id, 'code' => 'Murcia', 'name' => 'Murcia'],
            ['country_id' => $es->id, 'code' => 'Navarra', 'name' => 'Navarra'],
            ['country_id' => $es->id, 'code' => 'Ourense', 'name' => 'Ourense'],
            ['country_id' => $es->id, 'code' => 'Palencia', 'name' => 'Palencia'],
            ['country_id' => $es->id, 'code' => 'Pontevedra', 'name' => 'Pontevedra'],
            ['country_id' => $es->id, 'code' => 'Salamanca', 'name' => 'Salamanca'],
            ['country_id' => $es->id, 'code' => 'Santa Cruz de Tenerife', 'name' => 'Santa Cruz de Tenerife'],
            ['country_id' => $es->id, 'code' => 'Segovia', 'name' => 'Segovia'],
            ['country_id' => $es->id, 'code' => 'Sevilla', 'name' => 'Sevilla'],
            ['country_id' => $es->id, 'code' => 'Soria', 'name' => 'Soria'],
            ['country_id' => $es->id, 'code' => 'Tarragona', 'name' => 'Tarragona'],
            ['country_id' => $es->id, 'code' => 'Teruel', 'name' => 'Teruel'],
            ['country_id' => $es->id, 'code' => 'Toledo', 'name' => 'Toledo'],
            ['country_id' => $es->id, 'code' => 'Valencia', 'name' => 'Valencia'],
            ['country_id' => $es->id, 'code' => 'Valladolid', 'name' => 'Valladolid'],
            ['country_id' => $es->id, 'code' => 'Vizcaya', 'name' => 'Vizcaya'],
            ['country_id' => $es->id, 'code' => 'Zamora', 'name' => 'Zamora'],
            ['country_id' => $es->id, 'code' => 'Zaragoza', 'name' => 'Zaragoza'],
            ['country_id' => $fr->id, 'code' => '1', 'name' => 'Ain'],
            ['country_id' => $fr->id, 'code' => '2', 'name' => 'Aisne'],
            ['country_id' => $fr->id, 'code' => '3', 'name' => 'Allier'],
            ['country_id' => $fr->id, 'code' => '4', 'name' => 'Alpes-de-Haute-Provence'],
            ['country_id' => $fr->id, 'code' => '5', 'name' => 'Hautes-Alpes'],
            ['country_id' => $fr->id, 'code' => '6', 'name' => 'Alpes-Maritimes'],
            ['country_id' => $fr->id, 'code' => '7', 'name' => 'Ardèche'],
            ['country_id' => $fr->id, 'code' => '8', 'name' => 'Ardennes'],
            ['country_id' => $fr->id, 'code' => '9', 'name' => 'Ariège'],
            ['country_id' => $fr->id, 'code' => '10', 'name' => 'Aube'],
            ['country_id' => $fr->id, 'code' => '11', 'name' => 'Aude'],
            ['country_id' => $fr->id, 'code' => '12', 'name' => 'Aveyron'],
            ['country_id' => $fr->id, 'code' => '13', 'name' => 'Bouches-du-Rhône'],
            ['country_id' => $fr->id, 'code' => '14', 'name' => 'Calvados'],
            ['country_id' => $fr->id, 'code' => '15', 'name' => 'Cantal'],
            ['country_id' => $fr->id, 'code' => '16', 'name' => 'Charente'],
            ['country_id' => $fr->id, 'code' => '17', 'name' => 'Charente-Maritime'],
            ['country_id' => $fr->id, 'code' => '18', 'name' => 'Cher'],
            ['country_id' => $fr->id, 'code' => '19', 'name' => 'Corrèze'],
            ['country_id' => $fr->id, 'code' => '2A', 'name' => 'Corse-du-Sud'],
            ['country_id' => $fr->id, 'code' => '2B', 'name' => 'Haute-Corse'],
            ['country_id' => $fr->id, 'code' => '21', 'name' => 'Côte-d\'Or'],
            ['country_id' => $fr->id, 'code' => '22', 'name' => 'Côtes-d\'Armor'],
            ['country_id' => $fr->id, 'code' => '23', 'name' => 'Creuse'],
            ['country_id' => $fr->id, 'code' => '24', 'name' => 'Dordogne'],
            ['country_id' => $fr->id, 'code' => '25', 'name' => 'Doubs'],
            ['country_id' => $fr->id, 'code' => '26', 'name' => 'Drôme'],
            ['country_id' => $fr->id, 'code' => '27', 'name' => 'Eure'],
            ['country_id' => $fr->id, 'code' => '28', 'name' => 'Eure-et-Loir'],
            ['country_id' => $fr->id, 'code' => '29', 'name' => 'Finistère'],
            ['country_id' => $fr->id, 'code' => '30', 'name' => 'Gard'],
            ['country_id' => $fr->id, 'code' => '31', 'name' => 'Haute-Garonne'],
            ['country_id' => $fr->id, 'code' => '32', 'name' => 'Gers'],
            ['country_id' => $fr->id, 'code' => '33', 'name' => 'Gironde'],
            ['country_id' => $fr->id, 'code' => '34', 'name' => 'Hérault'],
            ['country_id' => $fr->id, 'code' => '35', 'name' => 'Ille-et-Vilaine'],
            ['country_id' => $fr->id, 'code' => '36', 'name' => 'Indre'],
            ['country_id' => $fr->id, 'code' => '37', 'name' => 'Indre-et-Loire'],
            ['country_id' => $fr->id, 'code' => '38', 'name' => 'Isère'],
            ['country_id' => $fr->id, 'code' => '39', 'name' => 'Jura'],
            ['country_id' => $fr->id, 'code' => '40', 'name' => 'Landes'],
            ['country_id' => $fr->id, 'code' => '41', 'name' => 'Loir-et-Cher'],
            ['country_id' => $fr->id, 'code' => '42', 'name' => 'Loire'],
            ['country_id' => $fr->id, 'code' => '43', 'name' => 'Haute-Loire'],
            ['country_id' => $fr->id, 'code' => '44', 'name' => 'Loire-Atlantique'],
            ['country_id' => $fr->id, 'code' => '45', 'name' => 'Loiret'],
            ['country_id' => $fr->id, 'code' => '46', 'name' => 'Lot'],
            ['country_id' => $fr->id, 'code' => '47', 'name' => 'Lot-et-Garonne'],
            ['country_id' => $fr->id, 'code' => '48', 'name' => 'Lozère'],
            ['country_id' => $fr->id, 'code' => '49', 'name' => 'Maine-et-Loire'],
            ['country_id' => $fr->id, 'code' => '50', 'name' => 'Manche'],
            ['country_id' => $fr->id, 'code' => '51', 'name' => 'Marne'],
            ['country_id' => $fr->id, 'code' => '52', 'name' => 'Haute-Marne'],
            ['country_id' => $fr->id, 'code' => '53', 'name' => 'Mayenne'],
            ['country_id' => $fr->id, 'code' => '54', 'name' => 'Meurthe-et-Moselle'],
            ['country_id' => $fr->id, 'code' => '55', 'name' => 'Meuse'],
            ['country_id' => $fr->id, 'code' => '56', 'name' => 'Morbihan'],
            ['country_id' => $fr->id, 'code' => '57', 'name' => 'Moselle'],
            ['country_id' => $fr->id, 'code' => '58', 'name' => 'Nièvre'],
            ['country_id' => $fr->id, 'code' => '59', 'name' => 'Nord'],
            ['country_id' => $fr->id, 'code' => '60', 'name' => 'Oise'],
            ['country_id' => $fr->id, 'code' => '61', 'name' => 'Orne'],
            ['country_id' => $fr->id, 'code' => '62', 'name' => 'Pas-de-Calais'],
            ['country_id' => $fr->id, 'code' => '63', 'name' => 'Puy-de-Dôme'],
            ['country_id' => $fr->id, 'code' => '64', 'name' => 'Pyrénées-Atlantiques'],
            ['country_id' => $fr->id, 'code' => '65', 'name' => 'Hautes-Pyrénées'],
            ['country_id' => $fr->id, 'code' => '66', 'name' => 'Pyrénées-Orientales'],
            ['country_id' => $fr->id, 'code' => '67', 'name' => 'Bas-Rhin'],
            ['country_id' => $fr->id, 'code' => '68', 'name' => 'Haut-Rhin'],
            ['country_id' => $fr->id, 'code' => '69', 'name' => 'Rhône'],
            ['country_id' => $fr->id, 'code' => '70', 'name' => 'Haute-Saône'],
            ['country_id' => $fr->id, 'code' => '71', 'name' => 'Saône-et-Loire'],
            ['country_id' => $fr->id, 'code' => '72', 'name' => 'Sarthe'],
            ['country_id' => $fr->id, 'code' => '73', 'name' => 'Savoie'],
            ['country_id' => $fr->id, 'code' => '74', 'name' => 'Haute-Savoie'],
            ['country_id' => $fr->id, 'code' => '75', 'name' => 'Paris'],
            ['country_id' => $fr->id, 'code' => '76', 'name' => 'Seine-Maritime'],
            ['country_id' => $fr->id, 'code' => '77', 'name' => 'Seine-et-Marne'],
            ['country_id' => $fr->id, 'code' => '78', 'name' => 'Yvelines'],
            ['country_id' => $fr->id, 'code' => '79', 'name' => 'Deux-Sèvres'],
            ['country_id' => $fr->id, 'code' => '80', 'name' => 'Somme'],
            ['country_id' => $fr->id, 'code' => '81', 'name' => 'Tarn'],
            ['country_id' => $fr->id, 'code' => '82', 'name' => 'Tarn-et-Garonne'],
            ['country_id' => $fr->id, 'code' => '83', 'name' => 'Var'],
            ['country_id' => $fr->id, 'code' => '84', 'name' => 'Vaucluse'],
            ['country_id' => $fr->id, 'code' => '85', 'name' => 'Vendée'],
            ['country_id' => $fr->id, 'code' => '86', 'name' => 'Vienne'],
            ['country_id' => $fr->id, 'code' => '87', 'name' => 'Haute-Vienne'],
            ['country_id' => $fr->id, 'code' => '88', 'name' => 'Vosges'],
            ['country_id' => $fr->id, 'code' => '89', 'name' => 'Yonne'],
            ['country_id' => $fr->id, 'code' => '90', 'name' => 'Territoire-de-Belfort'],
            ['country_id' => $fr->id, 'code' => '91', 'name' => 'Essonne'],
            ['country_id' => $fr->id, 'code' => '92', 'name' => 'Hauts-de-Seine'],
            ['country_id' => $fr->id, 'code' => '93', 'name' => 'Seine-Saint-Denis'],
            ['country_id' => $fr->id, 'code' => '94', 'name' => 'Val-de-Marne'],
            ['country_id' => $fr->id, 'code' => '95', 'name' => 'Val-d\'Oise'],
            ['country_id' => $ro->id, 'code' => 'AB', 'name' => 'Alba'],
            ['country_id' => $ro->id, 'code' => 'AR', 'name' => 'Arad'],
            ['country_id' => $ro->id, 'code' => 'AG', 'name' => 'Argeş'],
            ['country_id' => $ro->id, 'code' => 'BC', 'name' => 'Bacău'],
            ['country_id' => $ro->id, 'code' => 'BH', 'name' => 'Bihor'],
            ['country_id' => $ro->id, 'code' => 'BN', 'name' => 'Bistriţa-Năsăud'],
            ['country_id' => $ro->id, 'code' => 'BT', 'name' => 'Botoşani'],
            ['country_id' => $ro->id, 'code' => 'BV', 'name' => 'Braşov'],
            ['country_id' => $ro->id, 'code' => 'BR', 'name' => 'Brăila'],
            ['country_id' => $ro->id, 'code' => 'B', 'name' => 'Bucureşti'],
            ['country_id' => $ro->id, 'code' => 'BZ', 'name' => 'Buzău'],
            ['country_id' => $ro->id, 'code' => 'CS', 'name' => 'Caraş-Severin'],
            ['country_id' => $ro->id, 'code' => 'CL', 'name' => 'Călăraşi'],
            ['country_id' => $ro->id, 'code' => 'CJ', 'name' => 'Cluj'],
            ['country_id' => $ro->id, 'code' => 'CT', 'name' => 'Constanţa'],
            ['country_id' => $ro->id, 'code' => 'CV', 'name' => 'Covasna'],
            ['country_id' => $ro->id, 'code' => 'DB', 'name' => 'Dâmboviţa'],
            ['country_id' => $ro->id, 'code' => 'DJ', 'name' => 'Dolj'],
            ['country_id' => $ro->id, 'code' => 'GL', 'name' => 'Galaţi'],
            ['country_id' => $ro->id, 'code' => 'GR', 'name' => 'Giurgiu'],
            ['country_id' => $ro->id, 'code' => 'GJ', 'name' => 'Gorj'],
            ['country_id' => $ro->id, 'code' => 'HR', 'name' => 'Harghita'],
            ['country_id' => $ro->id, 'code' => 'HD', 'name' => 'Hunedoara'],
            ['country_id' => $ro->id, 'code' => 'IL', 'name' => 'Ialomiţa'],
            ['country_id' => $ro->id, 'code' => 'IS', 'name' => 'Iaşi'],
            ['country_id' => $ro->id, 'code' => 'IF', 'name' => 'Ilfov'],
            ['country_id' => $ro->id, 'code' => 'MM', 'name' => 'Maramureş'],
            ['country_id' => $ro->id, 'code' => 'MH', 'name' => 'Mehedinţi'],
            ['country_id' => $ro->id, 'code' => 'MS', 'name' => 'Mureş'],
            ['country_id' => $ro->id, 'code' => 'NT', 'name' => 'Neamţ'],
            ['country_id' => $ro->id, 'code' => 'OT', 'name' => 'Olt'],
            ['country_id' => $ro->id, 'code' => 'PH', 'name' => 'Prahova'],
            ['country_id' => $ro->id, 'code' => 'SM', 'name' => 'Satu-Mare'],
            ['country_id' => $ro->id, 'code' => 'SJ', 'name' => 'Sălaj'],
            ['country_id' => $ro->id, 'code' => 'SB', 'name' => 'Sibiu'],
            ['country_id' => $ro->id, 'code' => 'SV', 'name' => 'Suceava'],
            ['country_id' => $ro->id, 'code' => 'TR', 'name' => 'Teleorman'],
            ['country_id' => $ro->id, 'code' => 'TM', 'name' => 'Timiş'],
            ['country_id' => $ro->id, 'code' => 'TL', 'name' => 'Tulcea'],
            ['country_id' => $ro->id, 'code' => 'VS', 'name' => 'Vaslui'],
            ['country_id' => $ro->id, 'code' => 'VL', 'name' => 'Vâlcea'],
            ['country_id' => $ro->id, 'code' => 'VN', 'name' => 'Vrancea'],
            ['country_id' => $fi->id, 'code' => 'Lappi', 'name' => 'Lappi'],
            ['country_id' => $fi->id, 'code' => 'Pohjois-Pohjanmaa', 'name' => 'Pohjois-Pohjanmaa'],
            ['country_id' => $fi->id, 'code' => 'Kainuu', 'name' => 'Kainuu'],
            ['country_id' => $fi->id, 'code' => 'Pohjois-Karjala', 'name' => 'Pohjois-Karjala'],
            ['country_id' => $fi->id, 'code' => 'Pohjois-Savo', 'name' => 'Pohjois-Savo'],
            ['country_id' => $fi->id, 'code' => 'Etelä-Savo', 'name' => 'Etelä-Savo'],
            ['country_id' => $fi->id, 'code' => 'Etelä-Pohjanmaa', 'name' => 'Etelä-Pohjanmaa'],
            ['country_id' => $fi->id, 'code' => 'Pohjanmaa', 'name' => 'Pohjanmaa'],
            ['country_id' => $fi->id, 'code' => 'Pirkanmaa', 'name' => 'Pirkanmaa'],
            ['country_id' => $fi->id, 'code' => 'Satakunta', 'name' => 'Satakunta'],
            ['country_id' => $fi->id, 'code' => 'Keski-Pohjanmaa', 'name' => 'Keski-Pohjanmaa'],
            ['country_id' => $fi->id, 'code' => 'Keski-Suomi', 'name' => 'Keski-Suomi'],
            ['country_id' => $fi->id, 'code' => 'Varsinais-Suomi', 'name' => 'Varsinais-Suomi'],
            ['country_id' => $fi->id, 'code' => 'Etelä-Karjala', 'name' => 'Etelä-Karjala'],
            ['country_id' => $fi->id, 'code' => 'Päijät-Häme', 'name' => 'Päijät-Häme'],
            ['country_id' => $fi->id, 'code' => 'Kanta-Häme', 'name' => 'Kanta-Häme'],
            ['country_id' => $fi->id, 'code' => 'Uusimaa', 'name' => 'Uusimaa'],
            ['country_id' => $fi->id, 'code' => 'Itä-Uusimaa', 'name' => 'Itä-Uusimaa'],
            ['country_id' => $fi->id, 'code' => 'Kymenlaakso', 'name' => 'Kymenlaakso'],
            ['country_id' => $fi->id, 'code' => 'Ahvenanmaa', 'name' => 'Ahvenanmaa'],
            ['country_id' => $ee->id, 'code' => 'EE-37', 'name' => 'Harjumaa'],
            ['country_id' => $ee->id, 'code' => 'EE-39', 'name' => 'Hiiumaa'],
            ['country_id' => $ee->id, 'code' => 'EE-44', 'name' => 'Ida-Virumaa'],
            ['country_id' => $ee->id, 'code' => 'EE-49', 'name' => 'Jõgevamaa'],
            ['country_id' => $ee->id, 'code' => 'EE-51', 'name' => 'Järvamaa'],
            ['country_id' => $ee->id, 'code' => 'EE-57', 'name' => 'Läänemaa'],
            ['country_id' => $ee->id, 'code' => 'EE-59', 'name' => 'Lääne-Virumaa'],
            ['country_id' => $ee->id, 'code' => 'EE-65', 'name' => 'Põlvamaa'],
            ['country_id' => $ee->id, 'code' => 'EE-67', 'name' => 'Pärnumaa'],
            ['country_id' => $ee->id, 'code' => 'EE-70', 'name' => 'Raplamaa'],
            ['country_id' => $ee->id, 'code' => 'EE-74', 'name' => 'Saaremaa'],
            ['country_id' => $ee->id, 'code' => 'EE-78', 'name' => 'Tartumaa'],
            ['country_id' => $ee->id, 'code' => 'EE-82', 'name' => 'Valgamaa'],
            ['country_id' => $ee->id, 'code' => 'EE-84', 'name' => 'Viljandimaa'],
            ['country_id' => $ee->id, 'code' => 'EE-86', 'name' => 'Võrumaa'],
            ['country_id' => $lv->id, 'code' => 'LV-DGV', 'name' => 'Daugavpils'],
            ['country_id' => $lv->id, 'code' => 'LV-JEL', 'name' => 'Jelgava'],
            ['country_id' => $lv->id, 'code' => 'Jēkabpils', 'name' => 'Jēkabpils'],
            ['country_id' => $lv->id, 'code' => 'LV-JUR', 'name' => 'Jūrmala'],
            ['country_id' => $lv->id, 'code' => 'LV-LPX', 'name' => 'Liepāja'],
            ['country_id' => $lv->id, 'code' => 'LV-LE', 'name' => 'Liepājas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-REZ', 'name' => 'Rēzekne'],
            ['country_id' => $lv->id, 'code' => 'LV-RIX', 'name' => 'Rīga'],
            ['country_id' => $lv->id, 'code' => 'LV-RI', 'name' => 'Rīgas novads'],
            ['country_id' => $lv->id, 'code' => 'Valmiera', 'name' => 'Valmiera'],
            ['country_id' => $lv->id, 'code' => 'LV-VEN', 'name' => 'Ventspils'],
            ['country_id' => $lv->id, 'code' => 'Aglonas novads', 'name' => 'Aglonas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-AI', 'name' => 'Aizkraukles novads'],
            ['country_id' => $lv->id, 'code' => 'Aizputes novads', 'name' => 'Aizputes novads'],
            ['country_id' => $lv->id, 'code' => 'Aknīstes novads', 'name' => 'Aknīstes novads'],
            ['country_id' => $lv->id, 'code' => 'Alojas novads', 'name' => 'Alojas novads'],
            ['country_id' => $lv->id, 'code' => 'Alsungas novads', 'name' => 'Alsungas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-AL', 'name' => 'Alūksnes novads'],
            ['country_id' => $lv->id, 'code' => 'Amatas novads', 'name' => 'Amatas novads'],
            ['country_id' => $lv->id, 'code' => 'Apes novads', 'name' => 'Apes novads'],
            ['country_id' => $lv->id, 'code' => 'Auces novads', 'name' => 'Auces novads'],
            ['country_id' => $lv->id, 'code' => 'Babītes novads', 'name' => 'Babītes novads'],
            ['country_id' => $lv->id, 'code' => 'Baldones novads', 'name' => 'Baldones novads'],
            ['country_id' => $lv->id, 'code' => 'Baltinavas novads', 'name' => 'Baltinavas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-BL', 'name' => 'Balvu novads'],
            ['country_id' => $lv->id, 'code' => 'LV-BU', 'name' => 'Bauskas novads'],
            ['country_id' => $lv->id, 'code' => 'Beverīnas novads', 'name' => 'Beverīnas novads'],
            ['country_id' => $lv->id, 'code' => 'Brocēnu novads', 'name' => 'Brocēnu novads'],
            ['country_id' => $lv->id, 'code' => 'Burtnieku novads', 'name' => 'Burtnieku novads'],
            ['country_id' => $lv->id, 'code' => 'Carnikavas novads', 'name' => 'Carnikavas novads'],
            ['country_id' => $lv->id, 'code' => 'Cesvaines novads', 'name' => 'Cesvaines novads'],
            ['country_id' => $lv->id, 'code' => 'Ciblas novads', 'name' => 'Ciblas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-CE', 'name' => 'Cēsu novads'],
            ['country_id' => $lv->id, 'code' => 'Dagdas novads', 'name' => 'Dagdas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-DA', 'name' => 'Daugavpils novads'],
            ['country_id' => $lv->id, 'code' => 'LV-DO', 'name' => 'Dobeles novads'],
            ['country_id' => $lv->id, 'code' => 'Dundagas novads', 'name' => 'Dundagas novads'],
            ['country_id' => $lv->id, 'code' => 'Durbes novads', 'name' => 'Durbes novads'],
            ['country_id' => $lv->id, 'code' => 'Engures novads', 'name' => 'Engures novads'],
            ['country_id' => $lv->id, 'code' => 'Garkalnes novads', 'name' => 'Garkalnes novads'],
            ['country_id' => $lv->id, 'code' => 'Grobiņas novads', 'name' => 'Grobiņas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-GU', 'name' => 'Gulbenes novads'],
            ['country_id' => $lv->id, 'code' => 'Iecavas novads', 'name' => 'Iecavas novads'],
            ['country_id' => $lv->id, 'code' => 'Ikšķiles novads', 'name' => 'Ikšķiles novads'],
            ['country_id' => $lv->id, 'code' => 'Ilūkstes novads', 'name' => 'Ilūkstes novads'],
            ['country_id' => $lv->id, 'code' => 'Inčukalna novads', 'name' => 'Inčukalna novads'],
            ['country_id' => $lv->id, 'code' => 'Jaunjelgavas novads', 'name' => 'Jaunjelgavas novads'],
            ['country_id' => $lv->id, 'code' => 'Jaunpiebalgas novads', 'name' => 'Jaunpiebalgas novads'],
            ['country_id' => $lv->id, 'code' => 'Jaunpils novads', 'name' => 'Jaunpils novads'],
            ['country_id' => $lv->id, 'code' => 'LV-JL', 'name' => 'Jelgavas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-JK', 'name' => 'Jēkabpils novads'],
            ['country_id' => $lv->id, 'code' => 'Kandavas novads', 'name' => 'Kandavas novads'],
            ['country_id' => $lv->id, 'code' => 'Kokneses novads', 'name' => 'Kokneses novads'],
            ['country_id' => $lv->id, 'code' => 'Krimuldas novads', 'name' => 'Krimuldas novads'],
            ['country_id' => $lv->id, 'code' => 'Krustpils novads', 'name' => 'Krustpils novads'],
            ['country_id' => $lv->id, 'code' => 'LV-KR', 'name' => 'Krāslavas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-KU', 'name' => 'Kuldīgas novads'],
            ['country_id' => $lv->id, 'code' => 'Kārsavas novads', 'name' => 'Kārsavas novads'],
            ['country_id' => $lv->id, 'code' => 'Lielvārdes novads', 'name' => 'Lielvārdes novads'],
            ['country_id' => $lv->id, 'code' => 'LV-LM', 'name' => 'Limbažu novads'],
            ['country_id' => $lv->id, 'code' => 'Lubānas novads', 'name' => 'Lubānas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-LU', 'name' => 'Ludzas novads'],
            ['country_id' => $lv->id, 'code' => 'Līgatnes novads', 'name' => 'Līgatnes novads'],
            ['country_id' => $lv->id, 'code' => 'Līvānu novads', 'name' => 'Līvānu novads'],
            ['country_id' => $lv->id, 'code' => 'LV-MA', 'name' => 'Madonas novads'],
            ['country_id' => $lv->id, 'code' => 'Mazsalacas novads', 'name' => 'Mazsalacas novads'],
            ['country_id' => $lv->id, 'code' => 'Mālpils novads', 'name' => 'Mālpils novads'],
            ['country_id' => $lv->id, 'code' => 'Mārupes novads', 'name' => 'Mārupes novads'],
            ['country_id' => $lv->id, 'code' => 'Naukšēnu novads', 'name' => 'Naukšēnu novads'],
            ['country_id' => $lv->id, 'code' => 'Neretas novads', 'name' => 'Neretas novads'],
            ['country_id' => $lv->id, 'code' => 'Nīcas novads', 'name' => 'Nīcas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-OG', 'name' => 'Ogres novads'],
            ['country_id' => $lv->id, 'code' => 'Olaines novads', 'name' => 'Olaines novads'],
            ['country_id' => $lv->id, 'code' => 'Ozolnieku novads', 'name' => 'Ozolnieku novads'],
            ['country_id' => $lv->id, 'code' => 'LV-PR', 'name' => 'Preiļu novads'],
            ['country_id' => $lv->id, 'code' => 'Priekules novads', 'name' => 'Priekules novads'],
            ['country_id' => $lv->id, 'code' => 'Priekuļu novads', 'name' => 'Priekuļu novads'],
            ['country_id' => $lv->id, 'code' => 'Pārgaujas novads', 'name' => 'Pārgaujas novads'],
            ['country_id' => $lv->id, 'code' => 'Pāvilostas novads', 'name' => 'Pāvilostas novads'],
            ['country_id' => $lv->id, 'code' => 'Pļaviņu novads', 'name' => 'Pļaviņu novads'],
            ['country_id' => $lv->id, 'code' => 'Raunas novads', 'name' => 'Raunas novads'],
            ['country_id' => $lv->id, 'code' => 'Riebiņu novads', 'name' => 'Riebiņu novads'],
            ['country_id' => $lv->id, 'code' => 'Rojas novads', 'name' => 'Rojas novads'],
            ['country_id' => $lv->id, 'code' => 'Ropažu novads', 'name' => 'Ropažu novads'],
            ['country_id' => $lv->id, 'code' => 'Rucavas novads', 'name' => 'Rucavas novads'],
            ['country_id' => $lv->id, 'code' => 'Rugāju novads', 'name' => 'Rugāju novads'],
            ['country_id' => $lv->id, 'code' => 'Rundāles novads', 'name' => 'Rundāles novads'],
            ['country_id' => $lv->id, 'code' => 'LV-RE', 'name' => 'Rēzeknes novads'],
            ['country_id' => $lv->id, 'code' => 'Rūjienas novads', 'name' => 'Rūjienas novads'],
            ['country_id' => $lv->id, 'code' => 'Salacgrīvas novads', 'name' => 'Salacgrīvas novads'],
            ['country_id' => $lv->id, 'code' => 'Salas novads', 'name' => 'Salas novads'],
            ['country_id' => $lv->id, 'code' => 'Salaspils novads', 'name' => 'Salaspils novads'],
            ['country_id' => $lv->id, 'code' => 'LV-SA', 'name' => 'Saldus novads'],
            ['country_id' => $lv->id, 'code' => 'Saulkrastu novads', 'name' => 'Saulkrastu novads'],
            ['country_id' => $lv->id, 'code' => 'Siguldas novads', 'name' => 'Siguldas novads'],
            ['country_id' => $lv->id, 'code' => 'Skrundas novads', 'name' => 'Skrundas novads'],
            ['country_id' => $lv->id, 'code' => 'Skrīveru novads', 'name' => 'Skrīveru novads'],
            ['country_id' => $lv->id, 'code' => 'Smiltenes novads', 'name' => 'Smiltenes novads'],
            ['country_id' => $lv->id, 'code' => 'Stopiņu novads', 'name' => 'Stopiņu novads'],
            ['country_id' => $lv->id, 'code' => 'Strenču novads', 'name' => 'Strenču novads'],
            ['country_id' => $lv->id, 'code' => 'Sējas novads', 'name' => 'Sējas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-TA', 'name' => 'Talsu novads'],
            ['country_id' => $lv->id, 'code' => 'LV-TU', 'name' => 'Tukuma novads'],
            ['country_id' => $lv->id, 'code' => 'Tērvetes novads', 'name' => 'Tērvetes novads'],
            ['country_id' => $lv->id, 'code' => 'Vaiņodes novads', 'name' => 'Vaiņodes novads'],
            ['country_id' => $lv->id, 'code' => 'LV-VK', 'name' => 'Valkas novads'],
            ['country_id' => $lv->id, 'code' => 'LV-VM', 'name' => 'Valmieras novads'],
            ['country_id' => $lv->id, 'code' => 'Varakļānu novads', 'name' => 'Varakļānu novads'],
            ['country_id' => $lv->id, 'code' => 'Vecpiebalgas novads', 'name' => 'Vecpiebalgas novads'],
            ['country_id' => $lv->id, 'code' => 'Vecumnieku novads', 'name' => 'Vecumnieku novads'],
            ['country_id' => $lv->id, 'code' => 'LV-VE', 'name' => 'Ventspils novads'],
            ['country_id' => $lv->id, 'code' => 'Viesītes novads', 'name' => 'Viesītes novads'],
            ['country_id' => $lv->id, 'code' => 'Viļakas novads', 'name' => 'Viļakas novads'],
            ['country_id' => $lv->id, 'code' => 'Viļānu novads', 'name' => 'Viļānu novads'],
            ['country_id' => $lv->id, 'code' => 'Vārkavas novads', 'name' => 'Vārkavas novads'],
            ['country_id' => $lv->id, 'code' => 'Zilupes novads', 'name' => 'Zilupes novads'],
            ['country_id' => $lv->id, 'code' => 'Ādažu novads', 'name' => 'Ādažu novads'],
            ['country_id' => $lv->id, 'code' => 'Ērgļu novads', 'name' => 'Ērgļu novads'],
            ['country_id' => $lv->id, 'code' => 'Ķeguma novads', 'name' => 'Ķeguma novads'],
            ['country_id' => $lv->id, 'code' => 'Ķekavas novads', 'name' => 'Ķekavas novads'],
            ['country_id' => $lt->id, 'code' => 'LT-AL', 'name' => 'Alytaus Apskritis'],
            ['country_id' => $lt->id, 'code' => 'LT-KU', 'name' => 'Kauno Apskritis'],
            ['country_id' => $lt->id, 'code' => 'LT-KL', 'name' => 'Klaipėdos Apskritis'],
            ['country_id' => $lt->id, 'code' => 'LT-MR', 'name' => 'Marijampolės Apskritis'],
            ['country_id' => $lt->id, 'code' => 'LT-PN', 'name' => 'Panevėžio Apskritis'],
            ['country_id' => $lt->id, 'code' => 'LT-SA', 'name' => 'Šiaulių Apskritis'],
            ['country_id' => $lt->id, 'code' => 'LT-TA', 'name' => 'Tauragės Apskritis'],
            ['country_id' => $lt->id, 'code' => 'LT-TE', 'name' => 'Telšių Apskritis'],
            ['country_id' => $lt->id, 'code' => 'LT-UT', 'name' => 'Utenos Apskritis'],
            ['country_id' => $lt->id, 'code' => 'LT-VL', 'name' => 'Vilniaus Apskritis']
        ]);
    }
}
