<?php

use Illuminate\Database\Seeder;

class StatusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('statuses')->insert([
            [
                'text' => 'Submitted',
                'value' => 'submitted',
                'color' => '',
                'icon' => 'mdi-file-plus-outline',
                'can_checkout' => true,
                'can_edit_order_options' => true,
                'can_edit_order_items' => true,
                'can_receipt' => false,
                'can_mas_upload' => false,
                'can_mas_reupload' => false,
                'can_refund' => false,
                'can_cancel' => true,
            ],
            [
                'text' => 'Payment pending',
                'value' => 'payment_pending',
                'color' => 'secondary',
                'icon' => 'mdi-currency-usd-off',
                'can_checkout' => true,
                'can_edit_order_options' => true,
                'can_edit_order_items' => true,
                'can_receipt' => false,
                'can_mas_upload' => false,
                'can_mas_reupload' => false,
                'can_refund' => true,
                'can_cancel' => true,

            ],
            [
                'text' => 'Refund pending',
                'value' => 'refund_pending',
                'color' => 'deep-orange accent-2',
                'icon' => 'mdi-credit-card-refund-outline',
                'can_checkout' => false,
                'can_edit_order_options' => true,
                'can_edit_order_items' => true,
                'can_receipt' => false,
                'can_mas_upload' => true,
                'can_mas_reupload' => true,
                'can_refund' => true,
                'can_cancel' => true,
            ],
            [
                'text' => 'Paid',
                'value' => 'paid',
                'color' => 'teal',
                'icon' => 'mdi-currency-usd',
                'can_checkout' => false,
                'can_edit_order_options' => true,
                'can_edit_order_items' => true,
                'can_receipt' => true,
                'can_mas_upload' => true,
                'can_mas_reupload' => false,
                'can_refund' => true,
                'can_cancel' => true,
            ],
            [
                'text' => 'Completed',
                'value' => 'completed',
                'color' => 'success',
                'icon' => 'mdi-checkbox-marked-circle-outline',
                'can_checkout' => false,
                'can_edit_order_options' => false,
                'can_edit_order_items' => false,
                'can_receipt' => true,
                'can_mas_upload' => false,
                'can_mas_reupload' => false,
                'can_refund' => true,
                'can_cancel' => false,

            ],
            [
                'text' => 'Printed',
                'value' => 'printed',
                'color' => '',
                'icon' => 'mdi-printer-check',
                'can_checkout' => false,
                'can_edit_order_options' => false,
                'can_edit_order_items' => false,
                'can_receipt' => true,
                'can_mas_upload' => false,
                'can_mas_reupload' => true,
                'can_refund' => false,
                'can_cancel' => false,
            ],
            [
                'text' => 'Reprinted',
                'value' => 'reprinted',
                'color' => '',
                'icon' => 'mdi-printer-alert',
                'can_checkout' => false,
                'can_edit_order_options' => false,
                'can_edit_order_items' => false,
                'can_receipt' => false,
                'can_mas_upload' => false,
                'can_mas_reupload' => true,
                'can_refund' => true,
                'can_cancel' => true,
            ],
            [
                'text' => 'Beign processed',
                'value' => 'being_processed',
                'color' => '',
                'icon' => 'mdi-package-variant',
                'can_checkout' => false,
                'can_edit_order_options' => true,
                'can_edit_order_items' => true,
                'can_receipt' => true,
                'can_mas_upload' => false,
                'can_mas_reupload' => true,
                'can_refund' => true,
                'can_cancel' => true,
            ],
            [
                'text' => 'Processed',
                'value' => 'processed',
                'color' => '',
                'icon' => 'mdi-package-variant-closed',
                'can_checkout' => true,
                'can_edit_order_options' => true,
                'can_edit_order_items' => true,
                'can_receipt' => true,
                'can_mas_upload' => false,
                'can_mas_reupload' => true,
                'can_refund' => true,
                'can_cancel' => true,
            ],
            [
                'text' => 'Out',
                'value' => 'out',
                'color' => '',
                'icon' => 'mdi-truck-delivery-outline',
                'can_checkout' => true,
                'can_edit_order_options' => true,
                'can_edit_order_items' => true,
                'can_receipt' => true,
                'can_mas_upload' => false,
                'can_mas_reupload' => true,
                'can_refund' => false,
                'can_cancel' => false,
            ],
            [
                'text' => 'Canceled',
                'value' => 'canceled',
                'color' => 'error',
                'icon' => 'mdi-close-circle-outline',
                'can_checkout' => false,
                'can_edit_order_options' => false,
                'can_edit_order_items' => false,
                'can_receipt' => false,
                'can_mas_upload' => false,
                'can_mas_reupload' => false,
                'can_refund' => false,
                'can_cancel' => false,
            ],
            [
                'text' => 'Pending review',
                'value' => 'pending_review',
                'color' => '',
                'icon' => 'mdi-file-find-outline',
                'can_checkout' => false,
                'can_edit_order_options' => true,
                'can_edit_order_items' => true,
                'can_receipt' => true,
                'can_mas_upload' => false,
                'can_mas_reupload' => false,
                'can_refund' => true,
                'can_cancel' => true,
            ],
        ]);
    }
}
